import React, { FC, useEffect, useState } from 'react'
import Head from 'next/head'
import { useTheme } from 'next-themes'

import { Header, Footer } from '../components'
import Popover from '../components/popover'

interface Props {
    children: React.ReactNode
    meta: any
}

const Layout: FC<Props> = ({ children, meta: pageMeta }) => {
    const { theme, setTheme } = useTheme()
    const [menu, setMenu] = useState(false)
    const meta = {
        title: '',
        description: '',
        cardImage: ''
    }

    const onToggle = () => {
        setMenu(!menu)
        document.body.style.overflow = 'hidden'
    }

    useEffect(() => {
        if (menu) document.body.style.overflow = 'hidden'
        else document.body.style.overflow = 'visible'
    }, [menu])

    return (
        <>
            <Head>
                <meta charSet="utf-8" />
                <meta content="IE=edge" httpEquiv="X-UA-Compatible" />
                <meta content="width=device-width, initial-scale=1" name="viewport" />
                <meta name="description" content="Generated by create next app" />
                <meta name="robots" content="follow, index" />
                <link href="/favicon.ico" rel="icon" />
                <meta content={meta.description} name="description" />
                <meta property="og:type" content="website" />
                <meta property="og:site_name" content={meta.title} />
                <meta property="og:description" content={meta.description} />
                <meta property="og:title" content={meta.title} />
                <meta property="og:image" content={meta.cardImage} />
                <meta name="twitter:card" content="summary_large_image" />
                <meta name="twitter:site" content="ninjaturtlesapi" />
                <meta name="twitter:title" content={meta.title} />
                <meta name="twitter:description" content={meta.description} />
                <meta name="twitter:image" content={meta.cardImage} />
                <link rel="preconnect" href="https://fonts.googleapis.com" crossOrigin='true' />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
                <meta content="#ffffff" name="theme-color" />
                <meta content="#ffffff" name="msapplication-TileColor" />
                <title>{meta.title}</title>
            </Head>
            <Header onToggle={onToggle} />
            <main>{children}</main>
            <Footer />
            {menu && <Popover theme={theme} setTheme={setTheme} setMenu={setMenu} />}
        </>
    )
}

export default Layout
